### ISSUE TITLE
gelöschter Datensatz verbleibt in der Karte 

### ISSUE THREAD

**Issue by geoinformation-kreis-vg** [pkorduan/kvmobile#16]
Wenn man in der Karte einen Datensatz auswählt und diesen löscht, wird der delete Befehl zwar ins log geschrieben und beim nächsten synchronisieren ausgeführt aber bis dahin ist nicht erkenntlich, dass dieser Punkt gelöscht wurde/wird.
Dies führt beim Nutzer zu Verwirrung.
- der Datensatz sollte anschließend nicht mehr in der Karte angezeigt werden oder    
- Der Datensatz müsste, für den Nutzer, kenntlich gemacht werden. -->Z.B.  Punktsymbol auf Mülltonne ändern oder durchstreichen.

**Comment by pkorduan** [comment]
Ist korrigiert worden. Die gelöschten Datensätzen werden jetzt sofort nach dem Löschen sowohl in der FeatureListe als auch in der Karte gelöscht.
